import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '前端开发',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
    {
      type: 'category',
      label: '后端开发',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
    {
      type: 'category',
      label: '算法',
      items: [
        {
          type: 'autogenerated',
          dirName: 'algorithm',
        },
      ],
    },
    {
      type: 'category',
      label: '项目作品',
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        },
      ],
    },
  ],
};

export default sidebars;
